/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import Business.DBO4Util.DB4OUtil;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.NGODoctorOrganization;
import Business.Organization.Organization;
import Business.Organization.VolunteersOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AdminWorkRequest;
import Business.WorkQueue.WorkRequest;
import com.db4o.cs.internal.messages.Message;
import com.sun.xml.internal.org.jvnet.mimepull.MIMEMessage;
import com.twilio.sdk.TwilioRestClient;
import com.twilio.sdk.TwilioRestException;
import com.twilio.sdk.resource.factory.MessageFactory;
import java.awt.CardLayout;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLEncoder;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.*;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.http.NameValuePair;
import org.apache.http.message.BasicNameValuePair;
import javax.mail.MessagingException;
//import com.seaglasslookandfeel.*;
//import com.jtattoo.plaf.smart.SmartLookAndFeel;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Tarun
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private int amount = 0;
    
    public MainJFrame() {
        initComponents();
        system = dB4OUtil.retrieveSystem();
        logoutBtn.setEnabled(false);
        
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usernameTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        userProcessContainer = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        doctorRadioBtn = new javax.swing.JRadioButton();
        volunteerRadioBtn = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nameTxtField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        addressTxtField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cityComboBox = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        phoneTxtField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        maleRadioBtn = new javax.swing.JRadioButton();
        femaleRadioBtn = new javax.swing.JRadioButton();
        submitBtn = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        donateBtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        twentyFiveRBtn = new javax.swing.JRadioButton();
        fiftyRBtn = new javax.swing.JRadioButton();
        hundredRBtn = new javax.swing.JRadioButton();
        seventyFiveRBtn = new javax.swing.JRadioButton();
        twoFiftyRBtn = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        emailIdTxtField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HEALTHCARE FOR HOMELESS");
        setBackground(new java.awt.Color(51, 204, 255));

        jSplitPane1.setBackground(new java.awt.Color(51, 204, 255));
        jSplitPane1.setDividerLocation(300);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Username");

        usernameTxtField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Password");

        passwordField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        loginBtn.setBackground(new java.awt.Color(51, 51, 255));
        loginBtn.setText("Log In");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        logoutBtn.setBackground(new java.awt.Color(51, 51, 255));
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/healthcare_splash.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(usernameTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                        .addComponent(passwordField)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel17)
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginBtn)
                    .addComponent(logoutBtn))
                .addContainerGap(597, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        userProcessContainer.setBackground(new java.awt.Color(51, 204, 255));
        userProcessContainer.setLayout(new java.awt.CardLayout());

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Thousands of individuals find themselves homeless every year. Among them are chronically \nill adults, veterans, families with school-age children, and the elderly. They are the people \nwho stay in emergency shelters or motel rooms, eat in soup kitchens, or visit drop-in centers. \nThey are also the men and women who find themselves on the streets, trying to survive in \nmakeshift shelters under bridges, down alleyways, and behind city buildings.\n\nOver 12,000 homeless men, women, and children are cared Boston Health Care for the \nHomeless Program each year. We are committed to ensuring that every one of these \nindividuals has access to comprehensive health care, from preventative dental care to cancer\ntreatment. Our clinicians, case managers, and behavioral health professionals work in more\nthan 60 locations to deliver the highest quality health care to some of our community’s most \nvulnerable—and most resilient—citizens.  ");
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/Homeless_logo.gif"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/Volunteer_Homeless.jpg"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/Homeless Person.jpg"))); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/footer.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(224, 224, 224)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel5))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(671, 671, 671)
                        .addComponent(jLabel3)))
                .addGap(605, 605, 605))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabel18)
                .addContainerGap(294, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("ABOUT US", jPanel3);

        jPanel4.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Get Involved");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("PLEASE SELECT FOR WHICH YOU ARE APPLYING ");

        buttonGroup3.add(doctorRadioBtn);
        doctorRadioBtn.setText("DOCTOR");
        doctorRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorRadioBtnActionPerformed(evt);
            }
        });

        buttonGroup3.add(volunteerRadioBtn);
        volunteerRadioBtn.setText("VOLUNTEER");
        volunteerRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volunteerRadioBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("PERSONAL INFORMATION");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("FULL NAME");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("ADDRESS");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("CITY");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("PHONE NUMBER");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setText("GENDER");

        buttonGroup2.add(maleRadioBtn);
        maleRadioBtn.setText("MALE");

        buttonGroup2.add(femaleRadioBtn);
        femaleRadioBtn.setText("FEMALE");

        submitBtn.setText("SUBMIT");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/Volunteer Signup Banner.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(403, 403, 403)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jLabel6))
                            .addComponent(doctorRadioBtn)
                            .addComponent(volunteerRadioBtn)
                            .addComponent(jLabel8)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel13))
                                    .addGap(54, 54, 54)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nameTxtField)
                                        .addComponent(addressTxtField)
                                        .addComponent(cityComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(phoneTxtField)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(maleRadioBtn)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                            .addComponent(femaleRadioBtn))))
                                .addComponent(jLabel7))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(submitBtn))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel19)))
                .addContainerGap(2301, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(44, 44, 44)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(doctorRadioBtn)
                .addGap(18, 18, 18)
                .addComponent(volunteerRadioBtn)
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(nameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(addressTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel11))
                    .addComponent(cityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(phoneTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(maleRadioBtn)
                        .addComponent(femaleRadioBtn)))
                .addGap(73, 73, 73)
                .addComponent(submitBtn)
                .addGap(69, 69, 69))
        );

        jTabbedPane5.addTab("GET INVOLVED", jPanel4);

        jPanel5.setBorder(new javax.swing.border.MatteBorder(null));

        donateBtn.setBackground(new java.awt.Color(51, 51, 255));
        donateBtn.setText("DONATE NOW");
        donateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donateBtnActionPerformed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/Donation.PNG"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/Donation Question.PNG"))); // NOI18N

        twentyFiveRBtn.setBackground(new java.awt.Color(51, 51, 255));
        buttonGroup4.add(twentyFiveRBtn);
        twentyFiveRBtn.setText("$25");

        fiftyRBtn.setBackground(new java.awt.Color(51, 51, 255));
        buttonGroup4.add(fiftyRBtn);
        fiftyRBtn.setText("$50");

        hundredRBtn.setBackground(new java.awt.Color(51, 51, 255));
        buttonGroup4.add(hundredRBtn);
        hundredRBtn.setText("$100");

        seventyFiveRBtn.setBackground(new java.awt.Color(51, 51, 255));
        buttonGroup4.add(seventyFiveRBtn);
        seventyFiveRBtn.setText("$75");

        twoFiftyRBtn.setBackground(new java.awt.Color(51, 51, 255));
        buttonGroup4.add(twoFiftyRBtn);
        twoFiftyRBtn.setText("$250");
        twoFiftyRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoFiftyRBtnActionPerformed(evt);
            }
        });

        jLabel16.setText("EMAIL ID");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/Donation Banner.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel20))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jLabel15))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(twentyFiveRBtn)
                                .addGap(67, 67, 67)
                                .addComponent(fiftyRBtn)
                                .addGap(67, 67, 67)
                                .addComponent(seventyFiveRBtn)
                                .addGap(67, 67, 67)
                                .addComponent(hundredRBtn)
                                .addGap(67, 67, 67)
                                .addComponent(twoFiftyRBtn))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel16)
                                        .addGap(87, 87, 87)
                                        .addComponent(emailIdTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(donateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(2242, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel15)
                .addGap(30, 30, 30)
                .addComponent(jLabel14)
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(twentyFiveRBtn)
                    .addComponent(fiftyRBtn)
                    .addComponent(hundredRBtn)
                    .addComponent(seventyFiveRBtn)
                    .addComponent(twoFiftyRBtn))
                .addGap(43, 43, 43)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(emailIdTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(donateBtn)
                .addContainerGap(225, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("DONATE", jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5)
        );

        userProcessContainer.add(jPanel2, "card2");

        jSplitPane1.setRightComponent(userProcessContainer);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        //ImageIcon icon = createImageIcon("healthcare_splash.jpg");
        String userName = usernameTxtField.getText();
        
        // Get Password
        char[] passwordCharArray = passwordField.getPassword();
        String password = String.valueOf(passwordCharArray);

        UserAccount account = system.getUserAccountDirectory().authenticateUser(userName, password);
        Enterprise inEnterprise = null;
        Organization inOrganization = null;
        
        if(account == null) {// system level admin credential is null
            for(Network network: system.getNetworkList()) { // Inside the network loop
                for(Enterprise enterprise:network.getEntDirectory().getEnterpriseList()) { // traversing the enterprise directory
                    account = enterprise.getUserAccountDirectory().authenticateUser(userName, password);
                    if(account == null) { //check for Enterprise admin
                        for(Organization org:enterprise.getOrgDir().getOrganizationList()) { 
                            //traversing the organization directory
                            account = org.getUserAccountDirectory().authenticateUser(userName, password);
                            if(account != null) { // check for Organization admin
                                inEnterprise = enterprise;
                                inOrganization = org;
                                break;
                            }
                        }
                    }
                    else { // Enterprise admin found 
                        inEnterprise = enterprise;
                        break;
                    }
                
                    if(inOrganization !=null) {
                        break;
                    }
                }
                if(inEnterprise!=null) {
                    break;
                }
            }
        }
        if(account == null) {
            JOptionPane.showMessageDialog(this, "Invalid Credentials!!!", "WARNING", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else {
            //give work area
            CardLayout layout = (CardLayout)userProcessContainer.getLayout();
            userProcessContainer.add("TAB1", jPanel2);
            layout.next(userProcessContainer);
            userProcessContainer.add("workArea",account.getRole().createWorkArea(userProcessContainer, account, inOrganization, inEnterprise, system));
            layout.next(userProcessContainer);
        }
        loginBtn.setEnabled(false);
        logoutBtn.setEnabled(true);
        usernameTxtField.setEnabled(false);
        passwordField.setEnabled(false);
    }//GEN-LAST:event_loginBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        logoutBtn.setEnabled(false);
        usernameTxtField.setEnabled(true);
        passwordField.setEnabled(true);
        loginBtn.setEnabled(true);

        usernameTxtField.setText("");
        passwordField.setText("");

        userProcessContainer.removeAll();
        JPanel blankJP = new JPanel();
        userProcessContainer.add("blank", jPanel2);
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
        crdLyt.next(userProcessContainer);
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        //try {
            // TODO add your handling code here:
            
        String gender = null;
            String designation = null;
            if(doctorRadioBtn.isSelected()) {
                designation = "doctor";
            }
            else if(volunteerRadioBtn.isSelected()) {
                designation = "volunteer";
            }
            if(maleRadioBtn.isSelected()) {
                gender = "M";
            }
            else if(femaleRadioBtn.isSelected()) {
                gender = "F";
            }
            
        if((nameTxtField.getText().isEmpty()) || (!(nameTxtField.getText().matches("[a-zA-Z\\s]+")))) {
            JOptionPane.showMessageDialog(this, "Enter A Valid Name!!!");
        }
        else if((addressTxtField.getText().isEmpty()) || (!(addressTxtField.getText().matches("[a-zA-Z0-9\\s]+")))) {
            JOptionPane.showMessageDialog(this, "Enter A Valid Address!!!");
        }
        else if((phoneTxtField.getText().isEmpty()) || (!(phoneTxtField.getText().matches("\\d{10}")))) {
            JOptionPane.showMessageDialog(this, "Enter A Valid Phone Number!!!");
        }
        else if(!(designation.equalsIgnoreCase("doctor")) && (!(designation.equalsIgnoreCase("volunteer")))) {
            JOptionPane.showMessageDialog(this, "Select The Designation!!!");
        }
        else if(!(gender.equalsIgnoreCase("M")) && (!(gender.equalsIgnoreCase("F")))) {
            JOptionPane.showMessageDialog(this, "Select The Gender!!!");
        }
        else {
            String name = nameTxtField.getText();
            String address = addressTxtField.getText();
            Network network = (Network) cityComboBox.getSelectedItem();
            String phoneNo = phoneTxtField.getText();
            System.out.println(name);
            
            AdminWorkRequest request = new AdminWorkRequest();
            //WorkRequest request = new WorkRequest();
            //  request.setStatus("PENDING");
            request.setAddress(address);
            request.setApplicationStatus("PENDING");
            request.setDesignation(designation);
            request.setGender(gender);
            request.setName(name);
            System.out.println("NAAM KYA HAI " + request.getName());
            request.setPhoneNo(phoneNo);
            System.out.println("JUST BEFORE ADDING REQUEST");
            
            ArrayList<Employee> emp;
            Organization org = null;
            if(network.getEntDirectory().getEnterpriseList().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Enterprise Under Construction");
                
            }
            else {
            for(Enterprise enterprise:network.getEntDirectory().getEnterpriseList()) {
                //System.out.println("BHAAP" + enterprise.getName());
                if(enterprise.getEntType().getValue().equals(Enterprise.EnterpriseType.NGO_Clinics.getValue())) {
                    System.out.println("IN ENTERPRISE NGO CLINICS");
                    
                    
                    if(enterprise.getOrgDir().getOrganizationList().isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Organization Under Construction");
                        break;
                    }
                    else {
                    for(Organization organization : enterprise.getOrgDir().getOrganizationList()) {
                        if(designation.equals("doctor")) {
                            if(organization instanceof NGODoctorOrganization) {
                                //org = organization;
                                organization.getWorkQueue().getWorkRequestList().add(request);
                                System.out.println(organization.getName());
                                System.out.println("In Doctor");
                                JOptionPane.showMessageDialog(this, "Your Application is in Process");
                                TwilioRestClient client = new TwilioRestClient("ACd4d9c14696f348fe21e4506a5e7b14e3", "d83be392f0c78d3a493675bf8d7942f1");
            
                                List<NameValuePair> params = new ArrayList<NameValuePair>();
                                params.add(new BasicNameValuePair("To", "+18577076050"));
                                params.add(new BasicNameValuePair("From", "+19073122832"));
                                params.add(new BasicNameValuePair("Body", "Your Application Is Under Review"));
            
                                MessageFactory messageFactory = client.getAccount().getMessageFactory();
                                try {
                                    com.twilio.sdk.resource.instance.Message  message = (com.twilio.sdk.resource.instance.Message) messageFactory.create(params);
                                } catch (TwilioRestException ex) {
                                    Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
                                }
            
                                System.out.println("TRYING TO SEND MESSAGE");
                                //break;
                            }
                        }
                        else if (designation.equals("volunteer")) {
                            if(organization instanceof VolunteersOrganization) {
                                System.out.println(organization.getName());
                                System.out.println("In Volunteer");
                                // org = organization;
                                organization.getWorkQueue().getWorkRequestList().add(request);
                                JOptionPane.showMessageDialog(this, "Your Application is in Process");
                                TwilioRestClient client = new TwilioRestClient("ACd4d9c14696f348fe21e4506a5e7b14e3", "d83be392f0c78d3a493675bf8d7942f1");
            
                               List<NameValuePair> params = new ArrayList<NameValuePair>();
                                params.add(new BasicNameValuePair("To", "+18577076050"));
                                params.add(new BasicNameValuePair("From", "+19073122832"));
                                params.add(new BasicNameValuePair("Body", "Your Application Is Under Review"));
            
                                MessageFactory messageFactory = client.getAccount().getMessageFactory();
                                try {
                                    com.twilio.sdk.resource.instance.Message message = (com.twilio.sdk.resource.instance.Message) messageFactory.create(params);
                                } catch (TwilioRestException ex) {
                                    Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
                                }
            
                                System.out.println("TRYING TO SEND MESSAGE");
                                //break;
                            }
                        }
                    }
                }
                }
            }
            }
            }
            
            nameTxtField.setText("");
            addressTxtField.setText("");
            phoneTxtField.setText("");
            buttonGroup2.clearSelection();
//         } catch (TwilioRestException ex) {
//            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
    }//GEN-LAST:event_submitBtnActionPerformed

    private void doctorRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorRadioBtnActionPerformed
        // TODO add your handling code here:
        populateCityComboBox();
    }//GEN-LAST:event_doctorRadioBtnActionPerformed

    private void volunteerRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volunteerRadioBtnActionPerformed
        // TODO add your handling code here:
        populateCityComboBox();
    }//GEN-LAST:event_volunteerRadioBtnActionPerformed

    private void donateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donateBtnActionPerformed
        // TODO add your handling code here:
        
        String email = emailIdTxtField.getText();
        
        if(twentyFiveRBtn.isSelected()) {
            amount = 25;
        }
        else if(fiftyRBtn.isSelected()) {
            amount = 50;
        }
        else if(seventyFiveRBtn.isSelected()) {
            amount = 75;
        }
        else if(hundredRBtn.isSelected()) {
            amount = 100;
        }
        else if (twoFiftyRBtn.isSelected()) {
            amount = 250;
        }
        
        
        if(((emailIdTxtField.getText().isEmpty()) || (!(emailIdTxtField.getText().matches("^[A-Za-z0-9.%+\\-]+@[A-Za-z0-9.\\-]+\\.[A-Za-z]{2,4}$"))))) {
            JOptionPane.showMessageDialog(this, "Enter The Email ID!!!");
        }
        else if(amount<=0) {
            JOptionPane.showMessageDialog(this, "Enter The Donation Amount!!!");
        }
        else {
        system.addTotalDonation(amount);
        
        Properties props = new Properties();
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.socketFactor.port", "465");
        props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.port", "465");
        
        Session session=Session.getDefaultInstance(props,
         new javax.mail.Authenticator() {
             protected PasswordAuthentication getPasswordAuthentication(){
             return new PasswordAuthentication("northeastern1989@gmail.com", "abcxyz1989");
                
             } 
         
}        );
        
        try{
           javax.mail.Message message =  new MimeMessage(session);
           message.setFrom( new InternetAddress("keswani.tarun@gmail.com"));
           message.setRecipients(javax.mail.Message.RecipientType.TO, InternetAddress.parse(email));
           message.setSubject("DONATION");
           message.setText("Thank You, for the Donation of $" + amount);
           Transport.send(message);
           JOptionPane.showMessageDialog(this, "Email Sent");
       }
        
        catch(Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        }
    }//GEN-LAST:event_donateBtnActionPerformed

    private void twoFiftyRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoFiftyRBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twoFiftyRBtnActionPerformed

    public void populateCityComboBox() {
        cityComboBox.removeAllItems();
        if(system.getNetworkList().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Company Launch In Process!!!");
            submitBtn.setEnabled(false);
        }
        else {
        for(Network network : system.getNetworkList()) {
            cityComboBox.addItem(network);
            submitBtn.setEnabled(true);
        }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("NIMBUS".equals(info.getName())) {
                    System.out.println("BHAAAPPPP");
                    javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.texture.TextureLookAndFeel");
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                new MainJFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTxtField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox cityComboBox;
    private javax.swing.JRadioButton doctorRadioBtn;
    private javax.swing.JButton donateBtn;
    private javax.swing.JTextField emailIdTxtField;
    private javax.swing.JRadioButton femaleRadioBtn;
    private javax.swing.JRadioButton fiftyRBtn;
    private javax.swing.JRadioButton hundredRBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JRadioButton maleRadioBtn;
    private javax.swing.JTextField nameTxtField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField phoneTxtField;
    private javax.swing.JRadioButton seventyFiveRBtn;
    private javax.swing.JButton submitBtn;
    private javax.swing.JRadioButton twentyFiveRBtn;
    private javax.swing.JRadioButton twoFiftyRBtn;
    private javax.swing.JPanel userProcessContainer;
    private javax.swing.JTextField usernameTxtField;
    private javax.swing.JRadioButton volunteerRadioBtn;
    // End of variables declaration//GEN-END:variables
}
