/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.HospitalLab;

import Business.Enterprise.Enterprise;
import Business.Organization.LabOrganization;
import Business.Organization.Organization;
import Business.Patient.LabTest;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tarun
 */
public class LabAssistantWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form LabAssistantWorkArea
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private WorkRequest request;
    private Patient patient;
    private LabTest labTest;
    
    public LabAssistantWorkArea(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        
        populateLabQueueTable();
    }

    public void populateLabQueueTable() {
        DefaultTableModel model = (DefaultTableModel)labQueueTable.getModel();
        
        model.setRowCount(0);
        
        for(Organization organization : enterprise.getOrgDir().getOrganizationList()) {
            if(organization instanceof LabOrganization) {
                for(WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
                    Object[] row = new Object[7];
                    row[0] = request;
                    row[1] = request.getPatient();
                    row[2] = request.getSender();
                    row[3] = request.getReceiver();
                    row[4] = request.getRequestDate();
                    row[5] = request.getResolveDate();
                    row[6] = request.getStatus();
                    
                    model.addRow(row);
                 }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        labQueueTable = new javax.swing.JTable();
        assignToMeBtn = new javax.swing.JButton();
        processingBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        submitBtn = new javax.swing.JButton();
        urineTestCheckBox = new javax.swing.JCheckBox();
        urineTestLabel = new javax.swing.JLabel();
        ultraSoundCheckBox = new javax.swing.JCheckBox();
        xrayCheckBox = new javax.swing.JCheckBox();
        obesityCheckBox = new javax.swing.JCheckBox();
        cardioCheckBox = new javax.swing.JCheckBox();
        pulmonaryCheckBox = new javax.swing.JCheckBox();
        ctScanCheckBox = new javax.swing.JCheckBox();
        scoreCheckBox = new javax.swing.JCheckBox();
        diseaseCheckBox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        urineTestPass = new javax.swing.JRadioButton();
        urineTestFail = new javax.swing.JRadioButton();
        ultraSoundFail = new javax.swing.JRadioButton();
        xrayPass = new javax.swing.JRadioButton();
        ultraSoundPass = new javax.swing.JRadioButton();
        xrayFail = new javax.swing.JRadioButton();
        obesityFail = new javax.swing.JRadioButton();
        obesityPass = new javax.swing.JRadioButton();
        cardioFail = new javax.swing.JRadioButton();
        cardioPass = new javax.swing.JRadioButton();
        pulmanarFail = new javax.swing.JRadioButton();
        pulmanaryPass = new javax.swing.JRadioButton();
        ctscanPass = new javax.swing.JRadioButton();
        ctscanFail = new javax.swing.JRadioButton();
        scorePass = new javax.swing.JRadioButton();
        scoreFail = new javax.swing.JRadioButton();
        diseaseFail = new javax.swing.JRadioButton();
        diseasePass = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        diseasesTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labQueueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MESSAGE", "PATIENT", "SENDER", "RECEIVER", "REQUEST DATE", "RESOLVE DATE", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(labQueueTable);

        assignToMeBtn.setText("ASSIGN TO ME");
        assignToMeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignToMeBtnActionPerformed(evt);
            }
        });

        processingBtn.setText("PROCESSING");
        processingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processingBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(assignToMeBtn)
                        .addGap(28, 28, 28)
                        .addComponent(processingBtn)))
                .addContainerGap(481, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignToMeBtn)
                    .addComponent(processingBtn))
                .addContainerGap(425, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("LAB QUEUE", jPanel1);

        submitBtn.setText("SUBMIT");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        urineTestCheckBox.setEnabled(false);

        urineTestLabel.setText("URINE TEST");

        ultraSoundCheckBox.setEnabled(false);

        xrayCheckBox.setEnabled(false);

        obesityCheckBox.setEnabled(false);

        cardioCheckBox.setEnabled(false);

        pulmonaryCheckBox.setEnabled(false);

        ctScanCheckBox.setEnabled(false);

        scoreCheckBox.setEnabled(false);

        diseaseCheckBox.setEnabled(false);

        jLabel2.setText("DOPPLER ULTRASOUND");

        jLabel3.setText("PLAIN CHEST X-RAY");

        jLabel4.setText("OBESITY TEST");

        jLabel5.setText("ECHOCARDIOGRAPHY");

        jLabel6.setText("CARDIOPULMANARY TEST");

        jLabel7.setText("CT SCAN");

        jLabel8.setText("AGATSCON SCORE");

        jLabel9.setText("CORONARY ARTERY DISEASE");

        buttonGroup2.add(urineTestPass);
        urineTestPass.setText("PASS");
        urineTestPass.setEnabled(false);

        buttonGroup2.add(urineTestFail);
        urineTestFail.setText("FAIL");
        urineTestFail.setEnabled(false);

        buttonGroup3.add(ultraSoundFail);
        ultraSoundFail.setText("FAIL");
        ultraSoundFail.setEnabled(false);

        buttonGroup4.add(xrayPass);
        xrayPass.setText("PASS");
        xrayPass.setEnabled(false);

        buttonGroup3.add(ultraSoundPass);
        ultraSoundPass.setText("PASS");
        ultraSoundPass.setEnabled(false);

        buttonGroup4.add(xrayFail);
        xrayFail.setText("FAIL");
        xrayFail.setEnabled(false);

        buttonGroup11.add(obesityFail);
        obesityFail.setText("FAIL");
        obesityFail.setEnabled(false);

        buttonGroup11.add(obesityPass);
        obesityPass.setText("PASS");
        obesityPass.setEnabled(false);

        buttonGroup6.add(cardioFail);
        cardioFail.setText("FAIL");
        cardioFail.setEnabled(false);

        buttonGroup6.add(cardioPass);
        cardioPass.setText("PASS");
        cardioPass.setEnabled(false);

        buttonGroup7.add(pulmanarFail);
        pulmanarFail.setText("FAIL");
        pulmanarFail.setEnabled(false);

        buttonGroup7.add(pulmanaryPass);
        pulmanaryPass.setText("PASS");
        pulmanaryPass.setEnabled(false);

        buttonGroup8.add(ctscanPass);
        ctscanPass.setText("PASS");
        ctscanPass.setEnabled(false);

        buttonGroup8.add(ctscanFail);
        ctscanFail.setText("FAIL");
        ctscanFail.setEnabled(false);

        buttonGroup9.add(scorePass);
        scorePass.setText("PASS");
        scorePass.setEnabled(false);

        buttonGroup9.add(scoreFail);
        scoreFail.setText("FAIL");
        scoreFail.setEnabled(false);

        buttonGroup10.add(diseaseFail);
        diseaseFail.setText("FAIL");
        diseaseFail.setEnabled(false);

        buttonGroup10.add(diseasePass);
        diseasePass.setText("PASS");
        diseasePass.setEnabled(false);

        diseasesTextArea.setEditable(false);
        diseasesTextArea.setColumns(20);
        diseasesTextArea.setRows(5);
        jScrollPane2.setViewportView(diseasesTextArea);

        jLabel1.setText("TEST SUMMARY");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(urineTestCheckBox)
                    .addComponent(ultraSoundCheckBox)
                    .addComponent(xrayCheckBox)
                    .addComponent(obesityCheckBox)
                    .addComponent(cardioCheckBox)
                    .addComponent(diseaseCheckBox)
                    .addComponent(scoreCheckBox)
                    .addComponent(ctScanCheckBox)
                    .addComponent(pulmonaryCheckBox))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(submitBtn)))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cardioPass)
                                    .addComponent(obesityPass)
                                    .addComponent(diseasePass))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ctscanFail)
                                            .addComponent(scoreFail)
                                            .addComponent(diseaseFail))
                                        .addContainerGap(448, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pulmanarFail)
                                            .addComponent(cardioFail)
                                            .addComponent(obesityFail))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(scorePass)
                                    .addComponent(ctscanPass)
                                    .addComponent(pulmanaryPass))
                                .addContainerGap())))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(urineTestLabel)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(134, 134, 134)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(urineTestPass)
                                    .addComponent(ultraSoundPass)
                                    .addComponent(xrayPass))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(xrayFail)
                                    .addComponent(urineTestFail)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(ultraSoundFail)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1)))))
                        .addGap(138, 138, 138))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(urineTestLabel)
                                        .addComponent(urineTestPass)
                                        .addComponent(urineTestFail))
                                    .addComponent(urineTestCheckBox))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ultraSoundCheckBox)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(ultraSoundFail)
                                        .addComponent(ultraSoundPass)))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(xrayCheckBox)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(xrayPass)
                                        .addComponent(xrayFail)))
                                .addGap(178, 178, 178)
                                .addComponent(pulmanarFail))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(jLabel1)
                                .addGap(37, 37, 37)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(55, 55, 55)
                        .addComponent(ctscanFail))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(obesityCheckBox)
                            .addComponent(jLabel4)
                            .addComponent(obesityFail)
                            .addComponent(obesityPass))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cardioCheckBox)
                                .addComponent(jLabel5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cardioFail)
                                    .addComponent(cardioPass))
                                .addGap(5, 5, 5)))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pulmonaryCheckBox)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(pulmanaryPass)))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ctScanCheckBox)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(ctscanPass)))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scoreCheckBox)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(scorePass)
                                .addComponent(scoreFail)))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(diseaseCheckBox)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(diseaseFail)
                                .addComponent(diseasePass)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(submitBtn)
                .addGap(36, 36, 36))
        );

        jTabbedPane1.addTab("LAB RESULT", jPanel2);

        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void assignToMeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignToMeBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = labQueueTable.getSelectedRow();
        
        if(selectedRow >= 0) {
            this.request = (WorkRequest) labQueueTable.getValueAt(selectedRow, 0);
            String res = request.getReceiver() == null ? "EMPTY" : "OCCUPIED";
            if(res.equals("EMPTY") && (request.getStatus().equalsIgnoreCase("Sent To Lab"))) {
                request.setReceiver(userAccount);
                populateLabQueueTable();
            }
            else {
                JOptionPane.showMessageDialog(this, "Already Assigned To Lab");
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Select A Request!!!");
        }
    }//GEN-LAST:event_assignToMeBtnActionPerformed

    private void processingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processingBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = labQueueTable.getSelectedRow();
        if(selectedRow >= 0) {
            this.request = (WorkRequest) labQueueTable.getValueAt(selectedRow, 0);
            String res = request.getReceiver() == null ? "EMPTY" : "OCCUPIED";
            if(res.equals("OCCUPIED")) {
                if(request.getReceiver().equals(userAccount)) {
                    if(!(request.getStatus().equalsIgnoreCase("Pass")) && (!(request.getStatus().equalsIgnoreCase("Fail")))) {
                        patient = request.getPatient();
                        labTest = request.getLabTest();
                        if(!(labTest == null)) {
                        //for(LabTest labTest: patient.getLabTestList()) {
                            if(labTest.getStatus().equalsIgnoreCase("Processing")) {
                            if(!(labTest.getUrineTest()== null)) {
                                if(labTest.getUrineTest().equalsIgnoreCase("Urine Test")) {
                                    urineTestCheckBox.setSelected(true);
                                    urineTestPass.setEnabled(true);
                                    urineTestFail.setEnabled(true);
                                }
                            }
                            if(!(labTest.getUltraSound()== null)) {
                                if(labTest.getUltraSound().equalsIgnoreCase("Ultrasound")) {
                                    ultraSoundCheckBox.setSelected(true);
                                    ultraSoundFail.setEnabled(true);
                                    ultraSoundPass.setEnabled(true);
                                }
                            }
                            if(!(labTest.getxRay()== null)) { 
                                if(labTest.getxRay().equalsIgnoreCase("X-Ray")) {
                                    xrayCheckBox.setSelected(true);
                                    xrayFail.setEnabled(true);
                                    xrayPass.setEnabled(true);
                            }
                            }
                            if(!(labTest.getObesity()== null)) {
                                if(labTest.getObesity().equalsIgnoreCase("Obesity Test")) {
                                    obesityCheckBox.setSelected(true);
                                    obesityFail.setEnabled(true);
                                    obesityPass.setEnabled(true);
                                }
                            }
                            if(!(labTest.getCardioGraphy() == null)) {
                                if(labTest.getCardioGraphy().equalsIgnoreCase("EchoCardioGraphy")) {
                                    cardioCheckBox.setSelected(true);
                                    cardioFail.setEnabled(true);
                                    cardioPass.setEnabled(true);
                                }
                            }
                            if(!(labTest.getPulmonary() == null)) {
                                if(labTest.getPulmonary().equalsIgnoreCase("CardioPulmanary")) {
                                    pulmonaryCheckBox.setSelected(true);
                                    pulmanarFail.setEnabled(true);
                                    pulmanaryPass.setEnabled(true);
                                }
                            }
                            if(!(labTest.getCtScan() == null)) {
                                if(labTest.getCtScan().equalsIgnoreCase("CT Scan")) {
                                    ctScanCheckBox.setSelected(true);
                                    ctscanFail.setEnabled(true);
                                    ctscanPass.setEnabled(true);
                                }
                            }
                            if(!(labTest.getAgatsconScore() == null)) {
                                if(labTest.getAgatsconScore().equalsIgnoreCase("Agatscon Score")) {
                                    scoreCheckBox.setSelected(true);
                                    scoreFail.setEnabled(true);
                                    scorePass.setEnabled(true);
                            }
                            }
                            if(!(labTest.getArteryDisease()== null)) {
                                if(labTest.getArteryDisease().equalsIgnoreCase("Coronary Artery Disease")) {
                                    diseaseCheckBox.setSelected(true);
                                    diseaseFail.setEnabled(true);
                                    diseasePass.setEnabled(true);
                                }
                            }
                            }
                          //  break;
                            //}
                        }
                        jTabbedPane1.setSelectedIndex(1);
                        
                    }
                    else {
                    JOptionPane.showMessageDialog(this, "Test Already Completed!!!");
                }
            
                
            }
                else {
                    JOptionPane.showMessageDialog(this, "Test Under Another Lab Assistant Supervision");
                }
            }
            
            else {
                JOptionPane.showMessageDialog(this, "You Have Not Assigned The Request To Yourself!!!");
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Select A Request!!!");
        }
    }//GEN-LAST:event_processingBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        String heartDisease = null;
        String respRateDisease = null;
        String bpDisease = null;
        String weightDisease = null;
        String description = " ";
        
        
        UserAccount account;
        if(request == null) {
            JOptionPane.showMessageDialog(this, "Nothing to process");
        }
        else {
            if(urineTestCheckBox.isSelected()) {
                if(!(urineTestPass.isSelected())) {
                    heartDisease = "Heart Disease";
                }
            }
            if(ultraSoundCheckBox.isSelected()) {
                if(ultraSoundFail.isSelected()) {
                    respRateDisease = "Respiratory Disease";
                }
            }
            if(pulmonaryCheckBox.isSelected()) {
                if(pulmanarFail.isSelected()) {
                    respRateDisease = "Respiratory Disease";
                }
            }
            if(ctScanCheckBox.isSelected()) {
                if(ctscanFail.isSelected()) {
                    respRateDisease = "Respiratory Disease";
                }
            }
            if(cardioCheckBox.isSelected()) {
                if(cardioFail.isSelected()) {
                    heartDisease = "Heart Disease";
                }
            }
            if(urineTestCheckBox.isSelected()) {
                if(urineTestFail.isSelected()) {
                    heartDisease = "Heart Disease";
                }
            }
            if(xrayCheckBox.isSelected()) {
                if(xrayFail.isSelected()) {
                    heartDisease = "Heart Disease";
                }
            }
            if(scoreCheckBox.isSelected()) {
                if(scoreFail.isSelected()) {
                    bpDisease = "Blood Pressure Problem";
                }
            }
            if(diseaseCheckBox.isSelected()) {
                if(diseaseFail.isSelected()) {
                    bpDisease = "Blood Pressure Problem";
                }
            }
            if(obesityCheckBox.isSelected()) {
                if(obesityFail.isSelected()) {
                    weightDisease = "Fat Problem";
                }
            }
            
            
            
            if(!(respRateDisease == null)) {
                description = description + respRateDisease + " ";
            }
            if(!(heartDisease == null)) {
                description = description + heartDisease + " ";
            }
            if(!(weightDisease == null)) {
                description = description + weightDisease + " ";
            }
            if(!(bpDisease == null)) {
                description = description + bpDisease + " ";
            }
            
            if(description.equals(" ")) {
                description = "PASS";
                request.setMessage(description);
                diseasesTextArea.setText(description);
                request.setStatus("PASS");
                account = request.getSender();
                request.setSender(userAccount);
                request.setReceiver(account);
            }
            else {
                diseasesTextArea.setText(description);
                request.setMessage(description);
                request.setStatus("FAIL");
                labTest.setDescription(description);
                account = request.getSender();
                request.setSender(userAccount);
                request.setReceiver(account);
            }
        
        }
    }//GEN-LAST:event_submitBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignToMeBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JCheckBox cardioCheckBox;
    private javax.swing.JRadioButton cardioFail;
    private javax.swing.JRadioButton cardioPass;
    private javax.swing.JCheckBox ctScanCheckBox;
    private javax.swing.JRadioButton ctscanFail;
    private javax.swing.JRadioButton ctscanPass;
    private javax.swing.JCheckBox diseaseCheckBox;
    private javax.swing.JRadioButton diseaseFail;
    private javax.swing.JRadioButton diseasePass;
    private javax.swing.JTextArea diseasesTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable labQueueTable;
    private javax.swing.JCheckBox obesityCheckBox;
    private javax.swing.JRadioButton obesityFail;
    private javax.swing.JRadioButton obesityPass;
    private javax.swing.JButton processingBtn;
    private javax.swing.JRadioButton pulmanarFail;
    private javax.swing.JRadioButton pulmanaryPass;
    private javax.swing.JCheckBox pulmonaryCheckBox;
    private javax.swing.JCheckBox scoreCheckBox;
    private javax.swing.JRadioButton scoreFail;
    private javax.swing.JRadioButton scorePass;
    private javax.swing.JButton submitBtn;
    private javax.swing.JCheckBox ultraSoundCheckBox;
    private javax.swing.JRadioButton ultraSoundFail;
    private javax.swing.JRadioButton ultraSoundPass;
    private javax.swing.JCheckBox urineTestCheckBox;
    private javax.swing.JRadioButton urineTestFail;
    private javax.swing.JLabel urineTestLabel;
    private javax.swing.JRadioButton urineTestPass;
    private javax.swing.JCheckBox xrayCheckBox;
    private javax.swing.JRadioButton xrayFail;
    private javax.swing.JRadioButton xrayPass;
    // End of variables declaration//GEN-END:variables
}
