/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.SystemAdmin;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Person.Person;
import Business.Pharmacy.Order;
import Business.Pharmacy.OrderItem;
import Business.Role.AdminRole;
import Business.Role.NGOAdminRole;
import Business.Role.PharmacyAdminRole;
import Business.UserAccount.UserAccount;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Tarun
 */
public class SystemAdminWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkArea
     */
    private JPanel upc;
    private EcoSystem system;
    private DefaultCategoryDataset money;
    private int expenses;
    private String username;
    private String password;
    private String name;
    
    public SystemAdminWorkArea(JPanel upc, EcoSystem system) {
        initComponents();
        this.upc = upc;
        this.system = system;
        
        populateNetworkTable();
        populateTable();
        populateEntAdminTable();
        populateNetworkComboBox();
        populateEntTypeComboBox();
        populateNetAdminComboBox();
        
        totalDonationTxtField.setText(String.valueOf(system.getTotalDonation()));
        for(Order order: system.getMasterOrder().getOrderList()) {
            if(!(order.getOrderItem().isEmpty())) {
                for(OrderItem oi : order.getOrderItem()) {
            expenses = (int) (expenses + (oi.getDrug().getMarketPrice()*oi.getQuantity()));
        }
            }
        }
        totalExpenditureTxtField.setText(String.valueOf(expenses));
    }

    // Populate Networks Tab table
    public void populateNetworkTable() {
        DefaultTableModel model = (DefaultTableModel)nameTableField.getModel();
        
        model.setRowCount(0);
        
        for(Network network : system.getNetworkList()) {
            Object[] row = new Object[1];
            
            row[0] = network.getName();
            
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nameTableField = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        nameTxtField = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        entNetTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        networkComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        entTypeComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        entNameTxtField = new javax.swing.JTextField();
        submitEntBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        entAdminTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        netAdminComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        entAdminComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        usernameTxtField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        passwordTxtField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nameAdminTxtField = new javax.swing.JTextField();
        submitAdminBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        totalDonationTxtField = new javax.swing.JTextField();
        totalExpenditureTxtField = new javax.swing.JTextField();
        graphBtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        nameTableField.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NGO BRANCH LOCATIONS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(nameTableField);

        jLabel1.setText("BRANCH LOCATION");

        submitBtn.setText("SUBMIT");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/SystemAdmin/Network Banner.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addComponent(jLabel1)
                        .addGap(65, 65, 65)
                        .addComponent(nameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(526, 526, 526)
                        .addComponent(submitBtn)))
                .addContainerGap(676, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(submitBtn)
                .addContainerGap(405, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("NGO BRANCHES", jPanel1);

        entNetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NGO PARTNER", "NGO BRANCHES", "PARTNER NAME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(entNetTable);

        jLabel2.setText("NGO BRANCHES");

        jLabel3.setText("NGO PARTNERS");

        entTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        jLabel4.setText("PARTNER NAME");

        submitEntBtn.setText("SUBMIT");
        submitEntBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitEntBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(networkComboBox, 0, 150, Short.MAX_VALUE)
                            .addComponent(entTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(entNameTxtField)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(submitEntBtn)))))
                .addContainerGap(975, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(networkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(entTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(entNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(submitEntBtn)
                .addContainerGap(474, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("NGO PARTNERS", jPanel2);

        entAdminTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PARTNER NAME", "NGO BRANCHES", "ADMIN NAME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(entAdminTable);

        jLabel5.setText("NGO BRANCHES");

        netAdminComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netAdminComboBoxActionPerformed(evt);
            }
        });

        jLabel6.setText("PARTNER NAME");

        jLabel7.setText("USERNAME");

        jLabel8.setText("PASSWORD");

        jLabel9.setText("ADMIN NAME");

        submitAdminBtn.setText("SUBMIT");
        submitAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitAdminBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(427, 427, 427)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(98, 98, 98)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(netAdminComboBox, 0, 150, Short.MAX_VALUE)
                            .addComponent(entAdminComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(usernameTxtField)
                            .addComponent(passwordTxtField)
                            .addComponent(nameAdminTxtField)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(527, 527, 527)
                        .addComponent(submitAdminBtn)))
                .addContainerGap(960, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(netAdminComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(entAdminComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(usernameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(passwordTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nameAdminTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(submitAdminBtn)
                .addContainerGap(438, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PARTNERS ADMIN", jPanel3);

        jLabel10.setText("TOTAL DONATION");

        jLabel11.setText("TOTAL EXPENDITURE");

        totalDonationTxtField.setEditable(false);

        totalExpenditureTxtField.setEditable(false);

        graphBtn.setText("GRAPH");
        graphBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphBtnActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/SystemAdmin/funding banner.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(435, 435, 435)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(78, 78, 78)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(totalDonationTxtField)
                                    .addComponent(totalExpenditureTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(graphBtn))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel13)))
                .addContainerGap(516, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(totalDonationTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(totalExpenditureTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(163, 163, 163)
                .addComponent(graphBtn)
                .addGap(135, 135, 135))
        );

        jTabbedPane1.addTab("FUNDING REPORT", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        String name = nameTxtField.getText();
        int flag = 0;
        if(name.isEmpty()) {
          JOptionPane.showMessageDialog(this, "Enter The Name Of The City");
        }
        else if (!(name.matches("[a-zA-Z\\s]+"))) {
            JOptionPane.showMessageDialog(this, "Invalid Input");
            nameTxtField.setText("");
    }
        
        else {
        if(system.getNetworkList().isEmpty()) {
        Network network = system.addNetwork();
        network.setName(name);
        nameTxtField.setText("");
        populateNetworkTable();
        
        populateNetworkComboBox();
        
        populateEntTypeComboBox();
        }
        else {
            for(Network net : system.getNetworkList()) {
                if(net.getName().equalsIgnoreCase(name)) {
                    JOptionPane.showMessageDialog(this, "Branch Already Present At That Location"
                            + "!!!");
                    flag = 1;
                }
            }
            if(flag == 0) {
                Network network = system.addNetwork();
                network.setName(name);
                nameTxtField.setText("");
                JOptionPane.showMessageDialog(this, "Branch Location Added!!!");
                populateNetworkTable();
        
                populateNetworkComboBox();
        
                populateEntTypeComboBox();
            }
        }
        
        }   
    }//GEN-LAST:event_submitBtnActionPerformed

    private void submitEntBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitEntBtnActionPerformed
        // TODO add your handling code here:
            
        int flag =0 ;
        String entName = entNameTxtField.getText();
        Network network = (Network) networkComboBox.getSelectedItem();
        Enterprise.EnterpriseType type = (Enterprise.EnterpriseType) entTypeComboBox.getSelectedItem();
        if(network == null || type == null) {
            JOptionPane.showMessageDialog(this, "Invalid Input");
        }
        else if(!(entName.matches("[a-zA-Z\\s]+"))) {
            JOptionPane.showMessageDialog(this, "Invalid Entry");
        }
        else {
            if(!(network.getEntDirectory().getEnterpriseList().isEmpty())) {
            for(Enterprise ent : network.getEntDirectory().getEnterpriseList()) {
                if(ent.getName().equals(entName)) {
                    flag=1;
                }
            }
            }
            if(flag == 0) {
        Enterprise enterprise = network.getEntDirectory().addEnterprise(entName, type);
        
        JOptionPane.showMessageDialog(this, "Partner Added!!!");
        entNameTxtField.setText("");
        populateTable();
            
        
//        populateEntAdminTable();
        
        populateNetAdminComboBox();
            }
            else {
                JOptionPane.showMessageDialog(this, "Partner Already Associated With The NGO!!!");
            }
        }
    }//GEN-LAST:event_submitEntBtnActionPerformed

    public void populateEntAdminComboBox(Network network) {
        entAdminComboBox.removeAllItems();;
        
        if(!(network.getEntDirectory().getEnterpriseList().isEmpty())) {
        for(Enterprise enterprise:network.getEntDirectory().getEnterpriseList()) {
            entAdminComboBox.addItem(enterprise);
        }
        }
    }
    public void populateNetAdminComboBox() {
        netAdminComboBox.removeAllItems();
        
        if(!(system.getNetworkList().isEmpty())) {
        for(Network network:system.getNetworkList()) {
            netAdminComboBox.addItem(network);
        }
        }
    }
    private void submitAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitAdminBtnActionPerformed
        // TODO add your handling code here:
        Network network = (Network) netAdminComboBox.getSelectedItem();
        //Enterprise.EnterpriseType type = (Enterprise.EnterpriseType) entAdminComboBox.getSelectedItem();
        Enterprise enterprise = (Enterprise) entAdminComboBox.getSelectedItem();
        if(network == null) {
            JOptionPane.showMessageDialog(this, "Branch Location Not Present!!!");
        }
        else if(enterprise == null) {
            JOptionPane.showMessageDialog(this, "Partners Not Present!!!");
        }
        else if(usernameTxtField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter Valid Username!!!");
        }
        else if(passwordTxtField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter Valid Password!!!");
        }
        else if(nameAdminTxtField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter Valid Admin Name!!!");
        }
        else {
            username = usernameTxtField.getText();
            password = passwordTxtField.getText();
            name = nameAdminTxtField.getText();
        
        System.out.println(enterprise.getEntType().getValue());
        System.out.println(Enterprise.EnterpriseType.NGO_Clinics.getValue());
        int flag=0;
        if((nameAdminTxtField.getText().isEmpty()) || (!(nameAdminTxtField.getText().matches("[a-zA-Z\\s]+")))) {
            JOptionPane.showMessageDialog(this, "Invalid Admin Name!!!");
        } 
        else if((usernameTxtField.getText().isEmpty()) || (!(usernameTxtField.getText().matches("[a-zA-Z0-9]+")))) {
            JOptionPane.showMessageDialog(this, "Enter A Valid Username!!!");
        }
        else if((passwordTxtField.getText().isEmpty()) || (!(passwordTxtField.getText().matches("[a-zA-Z0-9]+")))) {
            JOptionPane.showMessageDialog(this, "Enter A Valid Password!!!");
        }
        else if(Enterprise.EnterpriseType.Hospital.getValue().equals(enterprise.getEntType().getValue())) {
            for(UserAccount account:enterprise.getUserAccountDirectory().getUserAccountList()) {
                if(account.getUsername().equalsIgnoreCase(username)) {
                    JOptionPane.showMessageDialog(this, "User Account Already Exists!!!");
                    flag =1;
                }
            }
            if (flag == 0) {
                Employee employee = new Employee();
                    ArrayList<Person> person;
                    person = enterprise.getPersonDirectory().getPersonList();
                
                    person.add(employee);
                    employee.setName(name);
            //Employee employee = enterprise.getEmployeeDirectory().createEmployee(name);
            UserAccount account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new AdminRole());
            usernameTxtField.setText("");
            passwordTxtField.setText("");
            nameAdminTxtField.setText("");
            }
        }
        else if(Enterprise.EnterpriseType.NGO_Clinics.getValue().equals(enterprise.getEntType().getValue())) {
            for(UserAccount account:enterprise.getUserAccountDirectory().getUserAccountList()) {
                if(account.getUsername().equalsIgnoreCase(username)) {
                    JOptionPane.showMessageDialog(this, "User Account Already Exists!!!");
                    flag =1;
                }
            }
            if(flag == 0) {
                Employee employee = new Employee();
                    ArrayList<Person> person;
                    person = enterprise.getPersonDirectory().getPersonList();
                    
                    person.add(employee);
                    employee.setName(name);
            //Employee employee = enterprise.getEmployeeDirectory().createEmployee(name);
            UserAccount account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new NGOAdminRole());
            usernameTxtField.setText("");
            passwordTxtField.setText("");
            nameAdminTxtField.setText("");
        }
        }
        else if(Enterprise.EnterpriseType.Pharmacy.getValue().equals(enterprise.getEntType().getValue())) {
            for(UserAccount account:enterprise.getUserAccountDirectory().getUserAccountList()) {
                if(account.getUsername().equalsIgnoreCase(username)) {
                    JOptionPane.showMessageDialog(this, "User Account Already Exists!!!");
                    flag =1;
                }
            }
            if(flag == 0) {
             Employee employee = new Employee();
                    ArrayList<Person> person;
                    person = enterprise.getPersonDirectory().getPersonList();
                    
                    person.add(employee);
                    employee.setName(name);
                    
            //Employee employee = enterprise.getEmployeeDirectory().createEmployee(name);
            UserAccount account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new PharmacyAdminRole());
            usernameTxtField.setText("");
            passwordTxtField.setText("");
            nameAdminTxtField.setText("");
        }
        }
        populateEntAdminTable();
        }
    }//GEN-LAST:event_submitAdminBtnActionPerformed

    private void netAdminComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netAdminComboBoxActionPerformed
        // TODO add your handling code here:
        
        Network network = (Network) netAdminComboBox.getSelectedItem();
        if(network != null) {
            populateEntAdminComboBox(network);
        }
    }//GEN-LAST:event_netAdminComboBoxActionPerformed

    private void graphBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphBtnActionPerformed
        // TODO add your handling code here:
        showGraph();
    }//GEN-LAST:event_graphBtnActionPerformed

    public void showGraph() {
        int count = 1;
        money = new DefaultCategoryDataset();
        int totalExpense = 0;
        
        for(Order order: system.getMasterOrder().getOrderList()) {
            if(!(order.getOrderItem().isEmpty())) {
                for(OrderItem oi: order.getOrderItem()) {
                    
                      totalExpense = (int) (totalExpense + (oi.getDrug().getMarketPrice()*oi.getQuantity()));
                      }
            }
        }
        String abc = String.valueOf(count);
        money.addValue(system.getTotalDonation(), "TOTAL FUNDING", abc);
        money.addValue(totalExpense, "TOTAL EXPENSES", abc);
        
        JFreeChart chartFactory = ChartFactory.createBarChart3D("GRAPHICAL REPRESENTATION OF FINANCES", "FUNDING/EXPENSE", "AMOUNT", money, PlotOrientation.VERTICAL, true, true, false);
        BarRenderer renderer = null;
        CategoryPlot plot = chartFactory.getCategoryPlot();
        renderer = new BarRenderer();
        ChartFrame frame = new ChartFrame("Bar Chart for Total Funding", chartFactory);
        frame.setVisible(true);
        frame.setSize(700, 320);
        
        
    }
    //Populating the Enterprise Admin Tab table
    public void populateEntAdminTable() {
        DefaultTableModel model = (DefaultTableModel)entAdminTable.getModel();
        
        model.setRowCount(0);
        if(!(system.getNetworkList().isEmpty())) {
        for(Network network:system.getNetworkList()) {
            for(Enterprise enterprise : network.getEntDirectory().getEnterpriseList()) {
                for(UserAccount account:enterprise.getUserAccountDirectory().getUserAccountList()) {
                Object[] row = new Object[3];
                row[0] = enterprise.getName();
                row[1] = network.getName();
                row[2] = account.getUsername();
                
                model.addRow(row);
                }
            }
        }
        }
    }
    
    // Populating Enterprise Tab table
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel)entNetTable.getModel();
        
        model.setRowCount(0);
        if(!(system.getNetworkList().isEmpty())) {
        for(Network network:system.getNetworkList()) {
            for(Enterprise enterprise : network.getEntDirectory().getEnterpriseList()) {
                Object[] row = new Object[3];
                row[0] = enterprise.getName();
                row[1] = network.getName();
                row[2] = enterprise.getEntType().getValue();
                
                model.addRow(row);
            }
        }
        }
    }
    public void populateEntTypeComboBox() {
        entTypeComboBox.removeAllItems();;
        
        for(Enterprise.EnterpriseType type: Enterprise.EnterpriseType.values()) {
            entTypeComboBox.addItem(type);
        }
    }
    public void populateNetworkComboBox() {
        networkComboBox.removeAllItems();
        
        if(!(system.getNetworkList().isEmpty())) {
        for(Network network:system.getNetworkList()) {
            networkComboBox.addItem(network);
        }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox entAdminComboBox;
    private javax.swing.JTable entAdminTable;
    private javax.swing.JTextField entNameTxtField;
    private javax.swing.JTable entNetTable;
    private javax.swing.JComboBox entTypeComboBox;
    private javax.swing.JButton graphBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nameAdminTxtField;
    private javax.swing.JTable nameTableField;
    private javax.swing.JTextField nameTxtField;
    private javax.swing.JComboBox netAdminComboBox;
    private javax.swing.JComboBox networkComboBox;
    private javax.swing.JTextField passwordTxtField;
    private javax.swing.JButton submitAdminBtn;
    private javax.swing.JButton submitBtn;
    private javax.swing.JButton submitEntBtn;
    private javax.swing.JTextField totalDonationTxtField;
    private javax.swing.JTextField totalExpenditureTxtField;
    private javax.swing.JTextField usernameTxtField;
    // End of variables declaration//GEN-END:variables
}
