/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ReceptionistRole;

import Business.Enterprise.Enterprise;
import Business.Organization.DonorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Tarun
 */


public class ReceptionistWorkAreaPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReceptionistWorkAreaPanel
     */
    
    private JPanel userProcessContainer;
    private Organization org;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private DonorOrganization donorOrg;
    
    public ReceptionistWorkAreaPanel(JPanel userProcessContainer, Organization org, Enterprise enterprise, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.org = org;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addDonorBtn = new javax.swing.JButton();
        manageDonorBtn = new javax.swing.JButton();
        donorHistoryBtn = new javax.swing.JButton();

        addDonorBtn.setText("ADD DONOR");
        addDonorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDonorBtnActionPerformed(evt);
            }
        });

        manageDonorBtn.setText("MANAGE DONOR");
        manageDonorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDonorBtnActionPerformed(evt);
            }
        });

        donorHistoryBtn.setText("DONOR HISTORY");
        donorHistoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donorHistoryBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(457, 457, 457)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(donorHistoryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageDonorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addDonorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(560, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(addDonorBtn)
                .addGap(132, 132, 132)
                .addComponent(manageDonorBtn)
                .addGap(100, 100, 100)
                .addComponent(donorHistoryBtn)
                .addContainerGap(321, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addDonorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDonorBtnActionPerformed
        // TODO add your handling code here:
        AddDonorJPanel adddonor = new AddDonorJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("AddDonorJPanel", adddonor);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addDonorBtnActionPerformed

    private void manageDonorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDonorBtnActionPerformed
        // TODO add your handling code here:
        DonorSelectionJPanel selectdonor = new DonorSelectionJPanel(userProcessContainer, org, enterprise, userAccount);
        userProcessContainer.add("DonorSelectionJPanel", selectdonor);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageDonorBtnActionPerformed

    private void donorHistoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donorHistoryBtnActionPerformed
        // TODO add your handling code here:
        DonorHistoryJPanel donorhistory = new DonorHistoryJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("DonorSelectionJPanel", donorhistory);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_donorHistoryBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDonorBtn;
    private javax.swing.JButton donorHistoryBtn;
    private javax.swing.JButton manageDonorBtn;
    // End of variables declaration//GEN-END:variables
}
