/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ReceptionistRole;

import Business.Enterprise.Enterprise;
import Business.Organization.DonorOrganization;
import Business.WorkQueue.LabTestWorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Tarun
 */
public class RequestBloodTestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestBloodTestJPanel
     */
    private JPanel userProcessContainer;
    private DonorOrganization donorOrg;
    private Enterprise enterprise;
    public RequestBloodTestJPanel(JPanel userProcessContainer, DonorOrganization donorOrg, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.donorOrg = donorOrg;
        this.enterprise = enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        messageTxtField = new javax.swing.JTextField();
        requestBloodBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("MESSAGE");

        requestBloodBtn.setText("Extract Blood");
        requestBloodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestBloodBtnActionPerformed(evt);
            }
        });

        jButton2.setText(">> BACK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(messageTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(174, 174, 174)
                        .addComponent(requestBloodBtn)))
                .addContainerGap(488, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(messageTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestBloodBtn)
                    .addComponent(jButton2))
                .addContainerGap(560, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestBloodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestBloodBtnActionPerformed
        // TODO add your handling code here:
        String message = messageTxtField.getText();
        if(message.equals("") || message.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter something to send.");
            return;
        }
        LabTestWorkRequest request = new LabTestWorkRequest();
        request.setMessage(message);
        //request.setDonor();
        request.setStatus("Sent");
    }//GEN-LAST:event_requestBloodBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField messageTxtField;
    private javax.swing.JButton requestBloodBtn;
    // End of variables declaration//GEN-END:variables
}
